import { ArrowUpRight, Bot, CornerDownLeft, RotateCcw, Sparkles, SlidersHorizontal } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { AnalysisReport, EvidenceType } from '../types';
import { askCodePulse } from '../lib/github';
import { Card, EvidencePill } from './Primitives';

export function AskCodePulse({ report }: { report: AnalysisReport }) {
  const [question, setQuestion] = useState(''); const [asked, setAsked] = useState('Why is the security score low?'); const [answer, setAnswer] = useState('Ask about security, testing, architecture, dependencies, or a specific finding and CodePulse will point to the evidence behind the signal.'); const [source, setSource] = useState<EvidenceType>('Heuristic analysis'); const [provider, setProvider] = useState<string | null>(null); const [loading, setLoading] = useState(false); const [providerUnavailable, setProviderUnavailable] = useState(false);
  useEffect(() => { void submitQuestion('Why is the security score low?'); }, [report]);
  async function submitQuestion(value: string) { const trimmed = value.trim(); if (!trimmed) return; setAsked(trimmed); setLoading(true); setProviderUnavailable(false); try { const result = await askCodePulse(report, trimmed); setAnswer(result.answer); setSource(result.source); setProvider(result.provider); setProviderUnavailable(Boolean(result.providerUnavailable)); } catch { setAnswer('Ask CodePulse is unavailable right now. Review the evidence panels and try again when the analysis service is online.'); setSource('Heuristic analysis'); setProvider(null); setProviderUnavailable(true); } finally { setLoading(false); } }
  function submit(event: React.FormEvent) { event.preventDefault(); void submitQuestion(question); setQuestion(''); }
  return <Card className="ask-card"><div className="ask-header"><div className="ask-avatar"><Bot size={18} /></div><div><span className="eyebrow">REPOSITORY-AWARE</span><h3>Ask CodePulse</h3></div><Sparkles size={16} className="ask-sparkle" /></div><p className="ask-subtitle">Get the why behind the score. Answers cite signals in this report, not generic advice.</p>{providerUnavailable && <div className="provider-unavailable"><strong>AI provider unavailable.</strong><span>Continue with the evidence-backed answer, retry the active provider, or switch providers.</span><div><button onClick={() => void submitQuestion(asked)}><RotateCcw size={12} /> Retry</button><button onClick={() => window.dispatchEvent(new CustomEvent('codepulse:open-settings'))}><SlidersHorizontal size={12} /> Switch provider</button><button onClick={() => setProviderUnavailable(false)}>Continue without AI</button></div></div>}<div className="answer-bubble"><div className="answer-label"><span>CodePulse</span><small>{loading ? 'thinking…' : provider || 'evidence mode'}</small></div><p>{answer}</p><EvidencePill source={source} /></div><form className="ask-form" onSubmit={submit}><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="e.g. Why is the security score low?" aria-label="Ask CodePulse a question" /><button type="submit" aria-label="Ask question" disabled={loading}><CornerDownLeft size={16} /></button></form><div className="ask-suggestions"><button onClick={() => void submitQuestion('Why is the security score low?')}>Why is security low? <ArrowUpRight size={12} /></button><button onClick={() => void submitQuestion('What should I test next?')}>What should I test next? <ArrowUpRight size={12} /></button></div><span className="ask-question-label">Last question: {asked}</span></Card>;
}
